---
proximity:
  help: "proximity, with larger numbers being closer proximity and vice versa",
  namespace: ""
  variable_labels: []
  const_labels: []

lux:
  help: "current ambient light level (lux)",
  namespace: ""
  variable_labels: []
  const_labels: []

pressure:
  help: "pressure Pressure measured (hPa)",
  namespace: ""
  variable_labels: []
  const_labels: []

humidity:
  help: "humidity Relative humidity measured (%)",
  namespace: ""
  variable_labels: []
  const_labels: []

temperature:
  help: "temperature Temperature measured (*C)",
  namespace: ""
  variable_labels: []
  const_labels: []

PM1:
  help: "Particulate Matter of diameter less than 1 micron. Measured in micrograms per cubic metre (ug/m3)",
  namespace: ""
  variable_labels: []
  const_labels: []