---
proximity:
  help: "proximity, with larger numbers being closer proximity and vice versa"
  metric: "proximity"
  namespace: ""
  variable_labels: []
  const_labels: []

lux:
  help: "current ambient light level (lux)"
  metric: "lux"
  namespace: ""
  variable_labels: []
  const_labels: []

pressure:
  help: "pressure Pressure measured (hPa)"
  metric: "pressure"
  namespace: ""
  variable_labels: []
  const_labels: []

humidity:
  help: "humidity Relative humidity measured (%)"
  metric: "humidity"
  namespace: ""
  variable_labels: []
  const_labels: []

temperature:
  help: "temperature Temperature measured (*C)"
  metric: "temperature"
  namespace: ""
  variable_labels: []
  const_labels: []

pm1:
  help: "Particulate Matter of diameter less than 1 micron. Measured in micrograms per cubic metre (ug/m3)"
  metric: "PM1"
  namespace: ""
  variable_labels: []
  const_labels: []

pm1_hist:
  help: "Histogram of Particulate Matter of diameter less than 1 micron measurements"
  metric: "pm1_measurements"
  namespace: ""
  variable_labels: []
  const_labels: []

pm25:
  help: "Particulate Matter of diameter less than 2.5 microns. Measured in micrograms per cubic metre (ug/m3)"
  metric: "PM25"
  namespace: ""
  variable_labels: []
  const_labels: []

pm25_hist:
  help: "Histogram of Particulate Matter of diameter less than 2.5 microns measurements"
  metric: "pm25_measurements"
  namespace: ""
  variable_labels: []
  const_labels: []

pm10:
  help: "Particulate Matter of diameter less than 10 microns. Measured in micrograms per cubic metre (ug/m3)"
  metric: "PM10"
  namespace: ""
  variable_labels: []
  const_labels: []

pm10_hist:
  help: "Histogram of Particulate Matter of diameter less than 10 microns measurements"
  metric: "pm10_measurements"
  namespace: ""
  variable_labels: []
  const_labels: []

nh3:
  help: "mostly Ammonia but could also include Hydrogen, Ethanol, Propane, Iso-butane (Ohms)"
  metric: "NH3"
  namespace: ""
  variable_labels: []
  const_labels: []

reducing:
  help: "Mostly carbon monoxide but could include H2S, Ammonia, Ethanol, Hydrogen, Methane, Propane, Iso-butane (Ohms)"
  metric: "reducing"
  namespace: ""
  variable_labels: []
  const_labels: []

oxidising:
  help: "Mostly nitrogen dioxide but could include NO and Hydrogen (Ohms)"
  metric: "oxidising"
  namespace: ""
  variable_labels: []
  const_labels: []
