// Code generated by `codegen` DO NOT EDIT.
package metrics

import (
	"github.com/prometheus/client_golang/prometheus"
)

type ExporterMetrics struct {
	Humidity *prometheus.Desc

	Lux *prometheus.Desc

	Nh3 *prometheus.Desc

	Oxidising *prometheus.Desc

	Pm1 *prometheus.Desc

	Pm10 *prometheus.Desc

	Pm25 *prometheus.Desc

	Pressure *prometheus.Desc

	Proximity *prometheus.Desc

	Reducing *prometheus.Desc

	Temperature *prometheus.Desc
}

func CreateExporterMetricPromDescriptors() *ExporterMetrics {
	return &ExporterMetrics{

		Humidity: prometheus.NewDesc(
			prometheus.BuildFQName("", "", "humidity"),
			"humidity Relative humidity measured (%)",
			[]string{},
			nil,
		),

		Lux: prometheus.NewDesc(
			prometheus.BuildFQName("", "", "lux"),
			"current ambient light level (lux)",
			[]string{},
			nil,
		),

		Nh3: prometheus.NewDesc(
			prometheus.BuildFQName("", "", "NH3"),
			"mostly Ammonia but could also include Hydrogen, Ethanol, Propane, Iso-butane (Ohms)",
			[]string{},
			nil,
		),

		Oxidising: prometheus.NewDesc(
			prometheus.BuildFQName("", "", "oxidising"),
			"Mostly nitrogen dioxide but could include NO and Hydrogen (Ohms)",
			[]string{},
			nil,
		),

		Pm1: prometheus.NewDesc(
			prometheus.BuildFQName("", "", "PM1"),
			"Particulate Matter of diameter less than 1 micron. Measured in micrograms per cubic metre (ug/m3)",
			[]string{},
			nil,
		),

		Pm10: prometheus.NewDesc(
			prometheus.BuildFQName("", "", "PM10"),
			"Particulate Matter of diameter less than 10 microns. Measured in micrograms per cubic metre (ug/m3)",
			[]string{},
			nil,
		),

		Pm25: prometheus.NewDesc(
			prometheus.BuildFQName("", "", "PM25"),
			"Particulate Matter of diameter less than 2.5 microns. Measured in micrograms per cubic metre (ug/m3)",
			[]string{},
			nil,
		),

		Pressure: prometheus.NewDesc(
			prometheus.BuildFQName("", "", "pressure"),
			"pressure Pressure measured (hPa)",
			[]string{},
			nil,
		),

		Proximity: prometheus.NewDesc(
			prometheus.BuildFQName("", "", "proximity"),
			"proximity, with larger numbers being closer proximity and vice versa",
			[]string{},
			nil,
		),

		Reducing: prometheus.NewDesc(
			prometheus.BuildFQName("", "", "reducing"),
			"Mostly carbon monoxide but could include H2S, Ammonia, Ethanol, Hydrogen, Methane, Propane, Iso-butane (Ohms)",
			[]string{},
			nil,
		),

		Temperature: prometheus.NewDesc(
			prometheus.BuildFQName("", "", "temperature"),
			"temperature Temperature measured (*C)",
			[]string{},
			nil,
		),
	}
}

func (m *ExporterMetrics) Describe(ch chan<- *prometheus.Desc) {

	ch <- m.Humidity

	ch <- m.Lux

	ch <- m.Nh3

	ch <- m.Oxidising

	ch <- m.Pm1

	ch <- m.Pm10

	ch <- m.Pm25

	ch <- m.Pressure

	ch <- m.Proximity

	ch <- m.Reducing

	ch <- m.Temperature

}
